wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.26
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.8.5
      5: 0.10.26
      8:
      - 5
batch_size:
  desc: null
  value: 128
beta 1:
  desc: null
  value: 0.5
beta 2:
  desc: null
  value: 0.999
init_lr:
  desc: null
  value: 0.0002
initialization_weights:
  desc: null
  value: Normal Distribution
noise_z_size:
  desc: null
  value: 128
train_images_count:
  desc: null
  value: 50000
